language: ruby
bundler_args: --without development
rvm:
  - 2.1.2
services:
  - mongodb
script:
  - bundle exec rspec spec
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: M2Mhwt7nSlgO/p8+kivByb3U123ZGhfzyBGmclRukKaxmFzGESliV0+51bbkCAPllEzpejsToy/XK4KZZm2rmThdGw4dVuZ7NaYwKEHjQjIEKTB7FdYTPIyNjSj3Ma3AKhhF7n8GQ6TrzAph783Rn+bPgPFoeMOYyhfza6bneHY=
  app: diamond-clinic
  on:
    repo: pboksz/diamond-clinic
