language: ruby
bundler_args: --without development
sudo: false
rvm: 2.2.0
services: mongodb
script: bundle exec rspec spec
addons:
  code_climate:
    repo_token:
      secure: cQfNt8d9zRVg8P4UKQZZmqlTCcZLE0xevfNgKUaZD+Hh10FcyCFDBgCbTfe5pUcV8fE+rPGHY8eGOSRSH8Gk24Nn/Zo9HpzFxh/aIuPt1Yz02j8t1KZAAtcm9WU/rhipOt75TaJPsZ66W4q0telVODdiET5OJzptObpwPcd7WNI=
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: M2Mhwt7nSlgO/p8+kivByb3U123ZGhfzyBGmclRukKaxmFzGESliV0+51bbkCAPllEzpejsToy/XK4KZZm2rmThdGw4dVuZ7NaYwKEHjQjIEKTB7FdYTPIyNjSj3Ma3AKhhF7n8GQ6TrzAph783Rn+bPgPFoeMOYyhfza6bneHY=
  app: diamond-clinic
  on:
    repo: pboksz/diamond-clinic
notifications:
  email: false
