development: &development
  secret_key_base: '1fbfcaf7306418403cca028c48c167a5cfcbd4575531ec6b423a88bfbf35b371191d02fe40964e4a26f3d948e88467ac609d4103dd7c0221d0b8b63ff3e62fce'
  email_from: 'hello@localhost'
  delivery_method: 'smtp'
  app_host:
    host: 'localhost'
    port: 3000
  smtp_settings:
    address: 'localhost'
    port: 1025
production:
  <<: *development
  secret_key_base: ENV['SECRET_KEY_BASE']
  email_from: 'biuro@diamondclinic.eu'
  delivery_method: 'smtp'
  app_host:
    host: 'diamondclinic.eu'
  smtp_settings:
    address: 'smtp.mandrillapp.com'
    port: 587
    user_name: ENV['MANDRILL_USERNAME']
    password: ENV['MANDRILL_APIKEY']
    domain: 'heroku.com'
    authentication: 'login'
test:
  <<: *development
  delivery_method: 'test'
  app_host:
    host: 'localhost'
    port: 3000
