development: &development
  email_regex: \A[^@\s]+@([^@\s]+\.)+[^@\s]+\z
  email_from: 'hello@localhost'
  delivery_method: 'smtp'
  asset_host: 'http://localhost:3000'
  app_host:
    host: 'localhost'
    port: 3000
  smtp_settings:
    address: 'localhost'
    port: 1025
production:
  <<: *development
  email_from: 'biuro@diamondclinic.eu'
  delivery_method: 'smtp'
  asset_host: 'http://diamondclinic.eu'
  app_host:
    host: 'diamondclinic.eu'
  smtp_settings:
    address: 'smtp.sendgrid.com'
    port: 587
    user_name: <%= ENV['SENDGRID_USERNAME'] %>
    password: <%= ENV['SENDGRID_PASSWORD'] %>
    domain: 'diamondclinic.eu'
    authentication: 'plain'
    enable_starttls_auto: true
test:
  <<: *development
  delivery_method: 'test'
  app_host:
    host: 'localhost'
    port: 3000
