development:
  sessions:
    default:
      database: diamond_clinic_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: diamond_clinic_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        safe: true
        max_retries: 10
        retry_interval: 30
