# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a46cdae3c2253d06aaa9ee6544fcb57d67a6290da51ef11dc4763fb79b1893937bc6470efc5efda9f23cb452143e1f3f27dba9cb7b89fa0ada63254666ca5104

test:
  secret_key_base: e85805758cd6111a1c66e9e11cb2f925e2b4e0d5e9cd288f23de3b4e77ffb2bb17838ec033bc5e6cf581b6016d9dcb958c4755d63aae16d87bf65206676154cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
